#include <iostream>
#include "controller.h"      // Generated by MATLAB Coder
#include "controller_impl.h" // Your TCP implementation header

int main() {
    // Number of clients to handle
    int numClients = 2;  // Example: change as needed

    std::cout << "Initializing TCP server...\n";

    // Call MATLAB-generated server function
    controller(numClients);

    std::cout << "Server finished.\n";
    return 0;
}
